on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install packages
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install

      - uses: mansagroup/nrwl-nx-action@v2.1.0
        with:
          targets: lint,build,test

      - uses: actions/upload-artifact@v2
        with:
          name: warthog
          path: dist/apps/warthog
          retention-days: 1

  check_artifacts:
    runs-on: ubuntu-latest
    needs: build
    outputs:
      warthog-exists: ${{ steps.check_warthog.outputs.files_exists }}

    steps:
      - uses: actions/download-artifact@v2

      - name: Check for warthog artifact
        id: check_warthog
        uses: andstor/file-existence-action@v1
        with:
          files: warthog

  deploy_warthog:
    if: needs.check_artifacts.outputs.warthog-exists == 'true'
    runs-on: ubuntu-latest
    needs: check_artifacts

    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: warthog
          path: apps/warthog/dist

      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'mld-warthog'
          heroku_email: 'mathieulegrasdev@gmail.com'
          appdir: 'apps/warthog'
